export const UPDATE_USER_APP_STATE = 'UPDATE_USER_APP_STATE';
export const GET_USER_BY_UID = 'GET_USER_BY_UID';
export const CLEAR_USER = 'CLEAR_USER';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_IMAGE = 'UPDATE_USER_PROFILE_IMAGE';
